name: MegaLinter
on:
  push:
  pull_request:
permissions:
  contents: write
jobs:
  megalinter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oxsecurity/megalinter@v8
        env:
          MEGALINTER_FLAVOR: all
          APPLY_FIXES: all
          APPLY_FIXES_EVENT: push
          APPLY_FIXES_MODE: commit
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
